'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {fetchWithTimeout} from '@/lib/client/fetch-with-timeout';
const interests=['concerts','festivals','school-events','campus-events','merchandise'];
export default function NotificationPreferences(){
 const[email,setEmail]=useState(false),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState('Loading your preferences…'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
 const mounted=useRef(false),loading=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{loading.current?.abort();const controller=new AbortController();loading.current=controller;setMessage('Loading your preferences…');try{const r=await fetchWithTimeout('/api/account/preferences',{signal:controller.signal});const b=await r.json();if(!r.ok)throw Error(r.status===401?'Sign in to manage your preferences.':'Preferences are unavailable. Please retry.');if(typeof b.preferences?.marketing_email!=='boolean'||!Array.isArray(b.preferences.event_interests)||b.preferences.event_interests.some((v:unknown)=>typeof v!=='string'||!interests.includes(v)))throw Error('Preferences are unavailable. Please retry.');if(!mounted.current||controller.signal.aborted)return;setEmail(b.preferences.marketing_email);setSelected(b.preferences.event_interests);setReady(true);setMessage('')}catch(e){if(mounted.current&&!controller.signal.aborted){setReady(false);setMessage(e instanceof Error?e.message:'Please retry.')}}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;loading.current?.abort()}},[load]);
 return <form className="booking-form" onSubmit={async e=>{e.preventDefault();if(!ready)return;setBusy(true);try{const r=await fetchWithTimeout('/api/account/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketing_email:email,event_interests:selected})});if(!r.ok)throw Error(r.status===401?'Sign in again to save preferences.':'Could not save. Your selection remains here; please retry.');if(mounted.current)setMessage('Preferences saved.')}catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'Could not save.')}finally{if(mounted.current)setBusy(false)}}}>
 <h2>Stay in the loop, your way.</h2><p>These choices control newsletter recipients. Transactional purchase confirmations remain enabled. No SMS or browser notifications are enabled.</p><label><input type="checkbox" checked={email} disabled={!ready||busy} onChange={e=>setEmail(e.target.checked)}/> Email me event and merchandise updates</label><fieldset disabled={!ready||busy}><legend>What interests you? Leave all unchecked for every topic.</legend>{interests.map(v=><label key={v}><input type="checkbox" checked={selected.includes(v)} onChange={e=>setSelected(s=>e.target.checked?[...s,v]:s.filter(x=>x!==v))}/>{v.replaceAll('-',' ')}</label>)}</fieldset><p role="status">{message}</p><button className="button" disabled={!ready||busy}>{busy?'Saving…':'Save preferences'}</button>{!ready&&<><button type="button" className="button secondary" onClick={()=>void load()}>Retry loading</button><a href="/account">Go to your account</a></>}
 </form>;
}
