'use client';
import {ShareActions} from './ShareActions';
import {useUrlFilters} from './useUrlFilters';
import {VideoRoll,Reels} from './ExperienceRails';
import {asset,MediaGallery,CommercialPortfolio,PartnersPortfolio,PortfolioHighlights,InstitutionStrip,MediaImage,PortfolioArrow} from './MediaLibrary';
import {EventDiscovery} from './EventDiscovery';
import {HeroMotion,AffiliatePreview,YouTubeFeature} from './ExperienceEnhancements';
import {PortfolioPage,ProofBoard,ExperiencePage,AboutPortfolio,SchoolDirectory} from './PortfolioExperience';
import {ContactPage} from './ContactInterface';
import {TourTimeline} from './TourTimeline';
import newsCategories from '../data/news-categories.json';import focusMetadata from '../data/image-focus.json';import {focalPosition} from '../lib/focal';import {InlineArrow} from './InlineArrow';import Link from './DocumentLink';import {useEffect,useRef,useState} from 'react';
type RecordData=Record<string,any>;type Props={path:string;query:Record<string,string|undefined>;screens:RecordData[];products:RecordData[];events:RecordData[];posts:RecordData[]};
const money=(n:number)=>`KES ${Number(n).toLocaleString('en-KE')}`;const photo=(name:string)=>({eugine:asset('M234').src,lucy:asset('M228').src,campus:asset('M120').src,performance:asset('M083').src,runway:asset('M082').src,hero:asset('M049').src,news:asset('M203').src}[name]||`/design-assets/${name}.${name==='logo'?'png':'jpg'}`);
function Pic({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){const ref=useRef<HTMLImageElement>(null);const [position,setPosition]=useState<string>();const metadata=(focusMetadata as Record<string,{x:number;y:number;source:string}>)[src.split('?')[0]];useEffect(()=>{const update=()=>{const image=ref.current;if(!image)return;if(!metadata||getComputedStyle(image).objectFit!=='cover'){setPosition(undefined);return}setPosition(focalPosition(metadata,image.naturalWidth,image.naturalHeight,image.clientWidth,image.clientHeight))};const image=ref.current;if(!image)return;const observer=new ResizeObserver(update);observer.observe(image);image.addEventListener('load',update);update();return()=>{observer.disconnect();image.removeEventListener('load',update)}},[src,metadata]);return <img ref={ref} className={className} src={src} alt={alt} loading={priority?'eager':'lazy'} decoding="async" style={position?{objectPosition:position}:undefined} data-focus-source={metadata?.source||'center'}/>}
function Arrow(){return <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function RollingLabel({children}:{children:React.ReactNode}){return <span className="rolling-label"><span className="rolling-front">{children}</span></span>}
function Button({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link className={`button ${light?'light':''}`} href={href}><RollingLabel>{children}</RollingLabel><Arrow/></Link>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function PageTitle({title,description,tag}:{title:string;description?:string;tag?:string}){return <section className="page-intro wrap"><div><Eyebrow>{tag||'Urban Gang Tour'}</Eyebrow><h1>{title.split(/<br\s*\/?>/).map((line,i)=><span key={i}>{i>0&&<br/>}{line}</span>)}</h1></div>{description&&<p>{description}</p>}</section>}
const faqs=[['Can you bring the tour to our school?','Yes. Tell us your school, preferred date and event format. We’ll discuss the programme, permissions, safeguarding requirements and a quote before confirming.'],['Can we book Eugine and Lucy on their own?','Yes. Request live hosting or a personal appearance through the booking form. Availability and fees are confirmed directly with you.'],['Do you host campus and public events?','We plan and host school, campus and public experiences. Talk to us about the audience, venue, production and ticketing you need.'],['Where do I buy tickets?','Tickets appear on the event page when the organizer opens sales. School-only events are clearly marked and are not public ticket sales.'],['What happens after I send a booking request?','The team reviews your event details and contacts you using the details you provide. Sending a request does not confirm a booking.']];
export default function Site({path,query,screens,products,events,posts}:Props){return <div className="public-page">{path==='/'?<Home events={events} products={products} posts={posts}/>:path==='/reels'?<Reels/>:path==='/portfolio'?<PortfolioPage/>:path==='/proof'?<ProofBoard/>:path==='/experience'?<ExperiencePage/>:path==='/tour-stops'?<TourTimeline/>:path==='/events'?<EventDiscovery events={events}/>:['/about','/the-gang'].includes(path)?<About/>:path.startsWith('/author/')?<Founder lucy={path.includes('lucy')}/>:path==='/gallery'||path.startsWith('/gallery/')?<MediaGallery slug={path.split('/')[2]}/>:path==='/work-with-us'?<CommercialPortfolio/>:['/clients','/partners'].includes(path)?<PartnersPortfolio/>:path==='/affiliates'?<AffiliatePreview/>:path==='/blog'?<News posts={posts}/>:path.startsWith('/blog/')?<Article post={posts.find(p=>p.id===path.split('/')[2])}/>:path==='/contact-us'?<ContactPage/>:path==='/faq'?<><PageTitle title="Before you book" description="Everything you need to know before joining the tour."/><FAQ/></>:<Missing title="This page has moved." href="/"/>}</div>;}

function Home({events,products,posts}:{events:RecordData[];products:RecordData[];posts:RecordData[]}){return <><section className="hero panel"><HeroVideo/><div className="hero-shade"/><div className="hero-inner"><div className="hero-heading"><h1>Urban<br/>Gang Tour.</h1><p>School, campus and live events.<br/>With Eugine Micah & Lucy Ogunde.</p></div><div className="hero-bottom"><Button href="/book" light>Plan your event</Button><Link className="hero-archive-credit" href="/gallery/uon-mr-miss-2022">Film archive · Mr & Miss UoN 2022 <PortfolioArrow/></Link></div></div></section>
<section className="section wrap"><div className="section-title"><Eyebrow>See the energy</Eyebrow><h2>From the crowd.<br/>To your next event.</h2></div><YouTubeFeature/></section><section className="section wrap" id="experiences"><div className="section-title"><Eyebrow>Events and services</Eyebrow><h2>Find the right event<br/>for your audience.</h2></div><div className="projects-grid home-experiences">{[{title:'The school tour',image:'/design-assets/school.jpg',tag:'Talent · Culture · Connection',href:'/tour-stops'},{title:'Campus events',image:asset('M120').src,tag:'Built for your community',href:'/experience'},{title:'Book Eugine & Lucy',image:asset('M203').src,tag:'Eugine & Lucy',href:'/book?type=hosts'}].map(p=><Link href={p.href} className="project-card reveal" key={p.title}><div className="project-caption"><strong>{p.title}</strong><small>{p.tag}</small><Arrow/></div><Pic src={p.image} alt={p.title}/></Link>)}</div><div className="center-action"><Button href="/events">View events</Button></div></section>
<InstitutionStrip/><VideoRoll ids={['M210','M213','M214','M215','M216','M219','M220']} title="Your audience. Their attention." description="Eugine Micah and Lucy Ogunde in real institutional and commercial campaigns. Explore the work, then brief us on your audience."/><PortfolioHighlights/><section className="people panel"><div className="section-title wrap"><Eyebrow>The people behind it</Eyebrow><h2>Meet Eugine<br/>and Lucy.</h2></div><div className="founders wrap"><Link href="/author/eugine-micah"><Pic src={photo("eugine")} alt="Eugine Micah"/><div><h3>Eugine Micah</h3><p>TV presenter · MC · Event host</p><Arrow/></div></Link><Link href="/author/lucy-ogunde"><Pic src={photo("lucy")} alt="Lucy Ogunde"/><div><h3>Lucy Ogunde</h3><p>TV presenter · MC · Event host</p><Arrow/></div></Link></div></section>
<section className="section wrap"><div className="section-title"><Eyebrow>Official merchandise</Eyebrow><h2>Shop tour merchandise</h2><p>Browse the live catalogue for current products, availability and prices.</p></div><Button href="/shop">Shop official merchandise</Button></section>
<section className="section wrap"><div className="section-title"><Eyebrow>From the tour</Eyebrow><h2>Latest news</h2></div><div className="news-grid">{posts.slice(0,3).map((p,i)=><Link className="news-card" href={`/blog/${p.id}`} key={p.id}><Pic src={asset(['M203','M229','M234'][i]).src} alt={p.headline}/><small>{newsCategory(p.id,p.section)?.label||p.section} · {p.date}</small><h3>{p.headline}</h3><Arrow/></Link>)}</div><div className="center-action"><Button href="/blog">Read the latest</Button></div></section><FAQ/><ContactBlock/></>}
function FAQ(){const [open,setOpen]=useState<number|null>(null);return <section className="faq-section section wrap"><div className="section-title"><Eyebrow>Before you book</Eyebrow><h2>What would you like to know?</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${open===i?'is-open':''}`} key={q}><h3><button className="faq-question" aria-expanded={open===i} aria-controls={`faq-answer-${i}`} onClick={()=>setOpen(open===i?null:i)}>{q}<span aria-hidden="true">+</span></button></h3><div className="faq-answer" id={`faq-answer-${i}`} aria-hidden={open!==i} inert={open!==i}><div><p>{a}</p></div></div></div>)}</div></section>}
function ContactBlock(){return null}

function About(){return <><PageTitle title="About Urban<br/>Gang Tour" description="We bring people together through events, talent, live hosting and the stories that follow." tag="Our story"/><section className="story-panel panel"><Pic src={asset("M073").src} alt="Mr & Miss UoN 2022 venue from the portfolio archive" priority/><div><Eyebrow>Urban Gang Tour</Eyebrow><h2>Events, hosting<br/>and merchandise</h2><p>We work with schools, campuses and communities to create experiences shaped around their people. Talent shows. Cultural days. Colour festivals. Live hosting that brings the room together.</p><p>Alongside the events, you’ll find our official merchandise, event discovery, ticketing and the stories from life on the road.</p><Button href="/experience">Explore what we do</Button></div></section><section className="section wrap"><div className="section-title"><Eyebrow>The people<br/>behind the energy</Eyebrow><h2>Meet our<br/>co-founders</h2></div><div className="founders"><Link href="/author/eugine-micah"><Pic src={photo("eugine")} alt="Eugine Micah"/><h3>Eugine Micah</h3><p>TV presenter · MC · Event host</p></Link><Link href="/author/lucy-ogunde"><Pic src={photo("lucy")} alt="Lucy Ogunde"/><h3>Lucy Ogunde</h3><p>TV presenter · MC · Event host</p></Link></div></section><AboutPortfolio/><ContactBlock/></>}
function Founder({lucy}:{lucy:boolean}){const name=lucy?'Lucy Ogunde':'Eugine Micah';const roles=lucy?['TV presenter','MC','Event host']:['TV presenter','MC','Event host','Hype man','Events coordinator','Events supplier'];return <><div className="breadcrumbs wrap"><Link href="/about">Our people</Link><span>/</span><span>{name}</span></div><section className="founder-detail wrap"><Pic src={asset(lucy?'M229':'M231').src} alt={name} priority/><div><Eyebrow>Urban Gang Tour · Co-founder</Eyebrow><h1>{name}</h1><p>{lucy?'Lucy Ogunde is a TV presenter, MC and event host. She brings conversation, audience connection and confident live presentation to school, campus and public events.':'Eugine Micah is a TV presenter, MC, event host and hype man. His work also includes event coordination and supplying the resources an event needs.'}</p><div className="role-tags">{roles.map(role=><span key={role}>{role}</span>)}</div><Button href={`/book?type=hosts&host=${lucy?'lucy':'eugine'}`}>Book {name}</Button><Link href="/portfolio">See the hosting portfolio</Link></div></section><section className="section wrap profile-services"><h2>What can you book {name} for?</h2><div className="service-grid">{[{title:'School & campus stages',text:'Talent shows, cultural days, student celebrations and campus programmes.'},{title:'Live hosting & presenting',text:'An MC for the programme, interviews, stage transitions and audience engagement.'},{title:lucy?'Community & brand appearances':'Coordination & event supply',text:lucy?'Discuss appearances and presenting for your campaign, institution or community.':'Discuss the programme, production requirements, supplier coordination and event-day delivery.'}].map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><p>Share the audience, date, location and role you need. Availability, scope and fees are agreed before confirmation.</p></section><section className="archive-callout wrap"><div><h2>On camera. On stage.</h2><p>Presenting and phone campaign photography from the supplied archive. Urban Gang Tour’s show airs on PPP TV.</p></div><Link className="button" href="/gallery/hosts-commercial">See campaign photography <InlineArrow/></Link></section><ContactBlock/></>}

function newsCategory(id:string,section=''){const mapped=(newsCategories.byPost as Record<string,string>)[id];const normalized=section.toLowerCase().trim();const fallback=/school|campus/.test(normalized)?'schools':/event|recap|concert|festival/.test(normalized)?'events':/talent|culture/.test(normalized)?'culture':/eugine|lucy|people|hosts/.test(normalized)?'people':/partner|sponsor/.test(normalized)?'partners':/update|tour/.test(normalized)?'updates':undefined;return newsCategories.categories.find(c=>c.id===(mapped||fallback)||c.label.toLowerCase()===normalized)}
function News({posts}:{posts:RecordData[]}){const [filters,updateFilters]=useUrlFilters({q:'',category:'all'},{category:['all',...newsCategories.categories.map(c=>c.id)]});const q=filters.q,category=filters.category;const setQ=(q:string)=>updateFilters({q},true);const setCategory=(category:string)=>updateFilters({category});const [limit,setLimit]=useState(12);const matches=posts.filter(p=>(category==='all'||newsCategory(p.id,p.section)?.id===category)&&`${p.headline} ${p.dek} ${p.section} ${p.id.replaceAll('-',' ')}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));return <><PageTitle title="Urban News" description="School stages, campus culture and the people making it happen." tag="Urban news"/><div className="wrap"><div className="filter-bar news-categories" role="group" aria-label="News categories">{[{id:'all',label:'All stories'},...newsCategories.categories].map(c=><button key={c.id} aria-pressed={category===c.id} className={category===c.id?'selected':''} onClick={()=>{setCategory(c.id);setLimit(12)}}>{c.label}</button>)}</div><label className="news-search"><span className="sr-only">Search stories</span><input type="search" placeholder="Search names, schools, culture or a topic" value={q} onChange={e=>{setQ(e.target.value);setLimit(12)}}/></label><div className="news-editorial-bar"><strong>Latest stories</strong><Link href="/book">Bring the next story to your school <InlineArrow/></Link></div><div className="news-grid">{matches.slice(0,limit).map(p=><Link className="news-card" key={p.id} href={`/blog/${p.id}`}><Pic src={p.img||'/design-assets/news.jpg'} alt={p.headline}/><small>{newsCategory(p.id,p.section)?.label||p.section} · {p.date}</small><h2>{p.headline}</h2><p>{p.dek}</p><Arrow/></Link>)}</div><p className="results-count" role="status">{Math.min(limit,matches.length)} of {matches.length} stories</p>{matches.length>limit&&<div className="center-action"><button className="button" onClick={()=>setLimit(x=>x+12)}>Show more stories</button></div>}{!matches.length&&<div className="empty-state"><h2>No matching stories</h2><p>Try a different name or topic.</p><button className="button secondary" onClick={()=>{updateFilters({q:'',category:'all'});setLimit(12)}}>Clear search</button></div>}</div><section className="section wrap video-section"><div className="section-title"><Eyebrow>In motion</Eyebrow><h2>Watch tour videos</h2></div><VideoPlayer/></section></>}
function VideoPlayer(){return <YouTubeFeature/>}
function Article({post:p}:{post:RecordData|undefined}){if(!p)return <Missing title="That story isn’t on this page." href="/blog"/>;return <><div className="breadcrumbs wrap"><Link href="/blog">News</Link><span>/</span><span>{p.section}</span></div><article className="article wrap"><Eyebrow>{newsCategory(p.id,p.section)?.label||p.section}</Eyebrow><h1>{p.headline}</h1><div className="article-meta"><Link href={p.id.includes('lucy')?'/author/lucy-ogunde':'/author/eugine-micah'}>{p.id.includes('lucy')?'Lucy Ogunde':'Eugine Micah'}</Link><time dateTime={p.date}>{p.date}</time></div><p className="dek">{p.dek}</p><p className="article-read-time">{Math.max(1,Math.ceil(String(p.body||p.dek).split(/\s+/).length/200))} min read</p><Pic src={p.img||'/design-assets/news.jpg'} alt={p.headline} priority/><div className="article-body">{(Array.isArray(p.body)?p.body:[p.body||p.dek]).map((t:string,i:number)=><p key={i}>{t.replace(/ and Hype Ola/g,'').replace(/alongside Eugine Micah and Hype Ola/g,'alongside Eugine Micah')}</p>)}</div><ShareActions title={p.headline} path={`/blog/${p.id}`} label="Share this story"/><Button href="/blog">More from the tour</Button></article></>}
function Missing({title,href}:{title:string;href:string}){return <div className="empty-state wrap"><h1>{title.split(/<br\s*\/?>/).map((line,i)=><span key={i}>{i>0&&<br/>}{line}</span>)}</h1><Button href={href}>Go back and explore</Button></div>}

function HeroVideo(){return <HeroMotion/>}
