'use client';
import {useEffect,useState} from 'react';
import {fetchWithTimeout} from '@/lib/client/fetch-with-timeout';
type Job={id:string;order_id:string;status:string;attempts:number;last_error:string|null;updated_at:string};
export default function EmailDeliveryPanel() {
  const [jobs,setJobs]=useState<Job[]>([]),[configured,setConfigured]=useState<boolean|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){setBusy(true);setError('');try{const r=await fetchWithTimeout('/api/admin/email-delivery',{cache:'no-store'});const d=await r.json();if(!Array.isArray(d.jobs)||(!r.ok&&d.configured!==false))throw new Error(d.error||'Could not load delivery status');setJobs(d.jobs);setConfigured(d.configured===true);}catch(e){setError(e instanceof Error?e.message:'Could not load delivery status');}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  async function retry(id:string){setBusy(true);try{const r=await fetchWithTimeout('/api/admin/email-delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.outcome||'Retry unavailable');await load();}catch(e){setError(e instanceof Error?e.message:'Retry unavailable');setBusy(false)}}
  return <section className="modern-card" aria-labelledby="email-delivery-title"><div className="modern-actions"><h3 id="email-delivery-title">Receipt email delivery</h3><button className="button secondary" onClick={load} disabled={busy}>{busy?'Checking…':'Refresh delivery status'}</button></div><p>Accepted means the email provider accepted the message. It does not confirm inbox delivery.</p>{configured===false&&<p role="alert">Email is not configured. Receipt jobs remain saved; configure the verified sending domain and server email key before retrying.</p>}{error&&<p role="alert">{error}</p>}{!jobs.length&&configured!==null&&<p>No receipt email jobs have been recorded.</p>}<div style={{display:'grid',gap:12}}>{jobs.map(job=><article key={job.id} style={{border:'1px solid #ddd',padding:12,borderRadius:12}}><strong>{job.order_id}</strong><p>{job.status} · {job.attempts} attempts{job.last_error?' · '+job.last_error.replaceAll('_',' '):''}</p><p>Updated {new Date(job.updated_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})}</p>{['queued','blocked'].includes(job.status)&&<button className="button secondary" disabled={busy||configured!==true} onClick={()=>retry(job.id)}>Retry saved receipt email</button>}{job.status==='failed'&&<p>Needs operator review. Automatic retries stopped to protect against duplicate delivery.</p>}</article>)}</div></section>;
}
