// Single source of truth — all schools, team, partners, news.
// To add a new school: push an object to SCHOOLS with id, name, date, county, tagline, description, motto.
// The router + CalendarSection + SchoolPage read from this.

window.UGT_DATA = {
  schools: [
    {
      id: 'koinange',
      name: 'Senior Chief Koinange Girls',
      shortName: 'Koinange Girls',
      date: '30 May 2026',
      dateShort: '30 MAY',
      county: 'Kiambu',
      town: 'Kiambaa, Kiambu County',
      tagline: 'Where the tour begins.',
      blurb: 'A historic national girls\' school in Kiambaa, Kiambu County — named for Senior Chief Koinange wa Mbiyu, one of Kenya\'s foundational community leaders. Long-known as a powerhouse for academics and student leadership. This is where the 2026 tour begins.',
      motto: 'To Serve',
      studentEstimate: '1,200+',
      principal: 'Office of the Principal',
      status: 'LOCKED',
      color: '#C7238E',
      eventNo: '01',
      theme: 'Find your voice.',
    },
    {
      id: 'loreto-kiambu',
      name: 'Loreto Kiambu Girls High',
      shortName: 'Loreto Kiambu',
      date: '1 June 2026',
      dateShort: '01 JUN',
      county: 'Kiambu',
      town: 'Kiambu Town, Kiambu County',
      tagline: 'Tradition meets the tour.',
      blurb: 'A storied Loreto Sisters-founded girls\' school in Kiambu Town. Known nationwide for a deeply rooted culture of academic excellence, drama, and music. Loreto girls have carried their school motto into every corner of Kenyan public life.',
      motto: 'Maria Regina',
      studentEstimate: '900+',
      principal: 'Office of the Principal',
      status: 'LOCKED',
      color: '#F5A623',
      eventNo: '02',
      theme: 'Own your story.',
    },
    {
      id: 'gathirimu',
      name: 'Gathirimu Girls Technical High',
      shortName: 'Gathirimu Girls',
      date: '4 July 2026',
      dateShort: '04 JUL',
      county: 'Kiambu',
      town: 'Githunguri, Kiambu County',
      tagline: 'Technical. Fearless. Futureproof.',
      blurb: 'A girls\' technical high school in Githunguri, Kiambu County — one of a small group of institutions giving young women a head start in the technical and applied sciences while still competing in the humanities. An audience built for UGT\'s Go Digital and Discover Your Talent pods.',
      motto: 'Excellence Through Skill',
      studentEstimate: '800+',
      principal: 'Office of the Principal',
      status: 'LOCKED',
      color: '#7B1FA2',
      eventNo: '03',
      theme: 'Skill is the superpower.',
    },
  ],

  hosts: [
    { name:'Eugine Micah', role:'Creative Director · Lead Host', photo:'assets/people/eugine-micah.png', bio:'Co-host of Urban News on PPP TV. Founder of Urban Gang Tour. Director of every TV episode.' },
    { name:'Lucy Ogunde', role:'Co-Host · MC', photo:'assets/people/lucy-ogunde.jpg', bio:'Co-host of Urban News. TV programme co-director. Voice of the tour.' },
  ],

  team: [
    { name:'MC Paps', role:'Coordination MC · Modelling', photo:'assets/people/mc-paps.webp', note:'CEO, Flip the Script' },
    { name:'Kalamu Nyeusi', role:'Stage Manager · Guest Poet', photo:'assets/people/kalamu-nyeusi.jpg', note:'Spoken word, Athi River' },
    { name:'Mark Davinci', role:'Head of Security', photo:'assets/people/mark-davinci.jpg', note:'Scouts · prefects · clubs' },
    { name:'DJ Xavi', role:'DJ Partner · DJ Coordinator', photo:'assets/people/dj-xavi.jpg', note:'TV presenter, PPP TV' },
    { name:'DJ JayJey', role:'DJ Partner', photo:'assets/people/dj-jayjey.jpg', note:'Celebrity social presence' },
    { name:'DJ Carian', role:'DJ · Experience Hub', photo:'assets/people/dj-carian.jpg', note:'Hype sets · sound support' },
    { name:'Hype Ola', role:'Hypeman · Experience Hub Lead', photo:'assets/people/hype-ola.jpg', note:'Leads the 30-person hub' },
    { name:'Gig Real', role:'Gospel Hypeman', photo:'assets/people/gig-real.webp', note:'Gospel hype · church support' },
    { name:'Rania Martin', role:'Social Content Lead', photo:'assets/people/rania-martin.webp', note:'8–12 reels per event' },
    { name:'George Morgan', role:'Camera Operator', photo:'assets/people/george-morgan.jpg', note:'Crowd · b-roll · winner interviews' },
    { name:'Tony Lallez', role:'Camera Operator · TV Segments', photo:'assets/people/tony-lallez.webp', note:'Shoots with hosts' },
    { name:'Pauline Masika', role:'Sound Engineer', photo:'assets/people/pauline-masika.jpg', note:'Lapels · PA · camera audio' },
    { name:'Mokaya Junior', role:'Content Creator · Student Speaker', photo:'assets/people/mokaya-junior.jpg', note:'Acclaimed influencer' },
  ],

  partners: [
    { name:'Destiny Life Church', role:'Co-production · Counselling · Tribez · Lit Gen', logo:'assets/logos/destiny-life-church.jpg', color:'#7B1FA2',
      detail:'Stage, sound, PAR can lights, setup crew, main keynote speaker, counselling tent, Tribez youth teams, Lit Gen DJ, transportation. UGT leadership are full members.' },
    { name:'PPP TV Kenya', role:'National Broadcaster · Urban News', logo:'assets/logos/ppp-tv.png', color:'#E91E63',
      detail:'Up to 8 million viewers. Every event becomes a 25–30 min Urban News episode. Daily reach: 400K–millions.' },
    { name:'The Experience Hub', role:'Hype · DJs · 5 Dancers · 30-person team', logo:null, color:'#C7238E',
      detail:'Led by Hype Ola with DJ Carian, 5 dancers (incl. Nyarangi & Jeff), and gospel hypeman Gig Real. Three high-energy sets per event.' },
    { name:'The Green Movement', role:'Tree Planting · Stewardship', logo:null, color:'#2E7D32',
      detail:'Led by Tai. Seedlings and guidance at every school. Scouts and Kenya Girl Guides take long-term stewardship.' },
    { name:'Faly Mark', role:'Events Partner · Stage & Sound', logo:null, color:'#F5A623',
      detail:'Our events company partner. Stage and sound equipment with 50/50 transport logistics cost-sharing.' },
    { name:'Urban News', role:'Our TV Show on PPP TV', logo:'assets/logos/urban-news.png', color:'#E53935',
      detail:'Hosted by Eugine Micah and Lucy Ogunde. The voice of UGT on national television.' },
  ],

  pods: [
    { n:'01', name:'Discover Your Talent', sub:'Performing arts · voice · craft' },
    { n:'02', name:'Own Your Money', sub:'Finance · entrepreneurship' },
    { n:'03', name:'Go Digital', sub:'Tech · AI · content creation' },
    { n:'04', name:'Lead From Where You Are', sub:'Leadership · agency · action' },
    { n:'05', name:'Mind Your Mind', sub:'Mental health · resilience · purpose' },
  ],

  categories: [
    'Choir','Gospel','Poetry','Drama','Rap','Dance','Comedy','Maths & Logic','Modelling',
  ],

  news: [
    { tag:'ANNOUNCEMENT', date:'12 APR 2026', title:'2nd Term Calendar Locked — 3 schools confirmed',
      excerpt:'Koinange Girls, Loreto Kiambu and Gathirimu Girls Tech are booked. Additional schools being added weekly.',
      color:'#C7238E' },
    { tag:'BROADCAST', date:'28 MAR 2026', title:'Urban News hits peak daily reach',
      excerpt:'Urban News on PPP TV crossed a new daily reach milestone during our term break recap series.',
      color:'#F5A623' },
    { tag:'PARTNERSHIP', date:'14 MAR 2026', title:'Destiny Life Church extends co-production to every event',
      excerpt:'Stage, sound, PAR can lights, full counselling tent, Tribez and Lit Gen continue as standing partners.',
      color:'#7B1FA2' },
    { tag:'AFTER THE TOUR', date:'2 MAR 2026', title:'Church Conference Day format confirmed',
      excerpt:'Category winners and top pod participants from all toured schools will reunite at Destiny Life Church grounds.',
      color:'#2E7D32' },
  ],

  stats: {
    ppp_reach: '8M',
    daily_reach: '400K+',
    crew_size: '30+',
    event_hours: '12.5',
    tv_segments: '8',
    reels_per_event: '8–12',
  },
};
