'use client';
import {ShareActions} from './ShareActions';
import {Newsletter} from './Newsletter';
import {useEffect,useState,useRef} from 'react';
import Link from './DocumentLink';
import seed from '../data/event-discovery.json';
import {rankEvents,reportedSales} from '../lib/event-ranking.mjs';
import timeline from '../data/tour-timeline.json';
const endpoint='https://urban-gang-tour-events.euginemicah.workers.dev/events';
type Listing=typeof seed.events[number];type Source=typeof seed.sources[number];type Feed={generatedAt:string;refreshSeconds:number;events:Listing[];sources:Source[];stale?:boolean};
const initial=seed as Feed;
const formatDate=(e:Listing)=>new Intl.DateTimeFormat('en-KE',{day:'numeric',month:'short',...(e.dateOnly?{}:{hour:'numeric',minute:'2-digit'}),timeZone:'Africa/Nairobi'}).format(new Date(e.dateOnly?e.startsAt+'T12:00:00+03:00':e.startsAt));
const price=(e:Listing)=>e.price===null?'Price on seller’s page':e.price===0?'Free · check registration':`${e.currency||'KES'} ${Number(e.price).toLocaleString('en-KE')}`;
function active(e:Listing,now:number){const start=Date.parse(e.dateOnly?e.startsAt+'T00:00:00+03:00':e.startsAt);const end=e.endsAt?Date.parse(e.endsAt.length===10?e.endsAt+'T23:59:59+03:00':e.endsAt):e.dateOnly?start+86400000:start;return end>now}
function entertainment(e:Listing){return ['Music & nightlife','Arts & culture'].includes(e.category)}
function Poster({e}:{e:Listing}){const [failed,setFailed]=useState(false);return <div className="discovery-poster">{!failed?<img src={e.image} alt={`${e.title} event poster`} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="poster-unavailable"><span>{e.sourceName}</span><strong>{e.title}</strong><small>Poster unavailable · view the event details</small></div>}</div>}
function Card({e,onInterest}:{e:Listing;onInterest?:(id:string,kind:string)=>void}){return <a className="discovery-card" onClick={()=>onInterest?.(e.id,'click')} href={e.url} target="_blank" rel="noopener noreferrer" aria-label={`${e.title}: view on ${e.sourceName}, opens in a new tab`}><Poster e={e}/><div className="discovery-card-copy"><div className="discovery-card-meta"><span>{e.category}</span><span>{e.sourceName}</span></div><time dateTime={e.startsAt}>{formatDate(e)}</time><h3>{e.title}</h3><p>{e.venue}</p><div className="discovery-card-action"><strong>{price(e)}</strong><span>View {e.sourceType==='Event guide'?'event':'tickets'} <svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19L19 5M6 5h13v13" fill="none" stroke="currentColor" strokeWidth="1.8"/></svg></span></div></div></a>}
export function EventDiscovery({events:ownEvents}:{events:Record<string,any>[]}){
 const [liveOwn,setLiveOwn]=useState(ownEvents);
 const [notice,setNotice]=useState('');const lastOwn=useRef(ownEvents.filter(e=>e.kind==='ticketed'&&e.status==='published').map(e=>String(e.id)).join(','));
 const [interest,setInterest]=useState<Record<string,{value:number;capturedAt:string}>>({});
 const counted=useRef(new Set<string>());
 function consented(){try{return JSON.parse(localStorage.getItem('ugt-new-preview-v1consent')||'null')==='accepted'}catch{return false}}
 function recordInterest(eventId:string,kind:string){const key=eventId+':'+kind;if(!consented()||counted.current.has(key))return;counted.current.add(key);fetch('/api/event-interest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId,kind,consent:true}),keepalive:true}).catch(()=>{})}
 async function updateInterest(signal:AbortSignal){try{const r=await fetch('/api/event-interest',{signal});if(!r.ok)return;const d=await r.json();if(!Array.isArray(d.signals)||!d.capturedAt)return;const map:Record<string,{value:number;capturedAt:string}>={};for(const row of d.signals){if(typeof row.key!=='string'||!Number.isFinite(row.value)||row.value<0)continue;const prev=map[row.key]?.value||0;map[row.key]={value:prev+row.value*(row.kind==='inquiry'?3:row.kind==='click'?2:1),capturedAt:d.capturedAt}}if(!signal.aborted)setInterest(map)}catch{}}

 const [feed,setFeed]=useState(initial),[state,setState]=useState('Checking latest listings'),[search,setSearch]=useState(''),[period,setPeriod]=useState('72'),[region,setRegion]=useState('Nairobi & nearby'),[category,setCategory]=useState('All categories'),[source,setSource]=useState('All sources'),[sort,setSort]=useState('recommended'),[featuredSource,setFeaturedSource]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>{let stopped=false,controller:AbortController|undefined,retry:ReturnType<typeof setTimeout>|undefined;async function refresh(){if(document.hidden)return;controller?.abort();controller=new AbortController();void updateInterest(controller.signal);const timeout=setTimeout(()=>controller?.abort(),12000);try{
void fetch('/api/site-data/events',{signal:AbortSignal.timeout(10000)}).then(async r=>{if(r.ok){const d=await r.json();if(!stopped&&Array.isArray(d.events)){setLiveOwn(d.events);const key=d.events.filter((e:any)=>e.kind==='ticketed'&&e.status==='published').map((e:any)=>String(e.id)).join(',');if(key&&key!==lastOwn.current)setNotice('New Urban Gang Tour events are available. Explore our featured event above.');lastOwn.current=key}}}).catch(()=>{});
const response=await fetch(endpoint,{signal:controller.signal});if(!response.ok)throw new Error('Unavailable');const data=await response.json();if(!Array.isArray(data.events)||!Array.isArray(data.sources))throw new Error('Invalid feed');if(stopped)return;setFeed(data);setState(data.stale?'Showing cached listings · updating':'Latest source check complete');if(data.stale)retry=setTimeout(refresh,15000)}catch{if(!stopped)setState('Showing saved listings · live update unavailable')}finally{clearTimeout(timeout)}}refresh();const poll=setInterval(refresh,180000),clock=setInterval(()=>setNow(Date.now()),60000);const onVisible=()=>{if(!document.hidden)refresh()};document.addEventListener('visibilitychange',onVisible);return()=>{stopped=true;controller?.abort();clearInterval(poll);clearInterval(clock);clearTimeout(retry);document.removeEventListener('visibilitychange',onVisible)}},[]);

 useEffect(()=>{if(!search.trim())return;const timer=setTimeout(()=>{const matches=feed.events.filter(e=>active(e,Date.now())&&`${e.title} ${e.venue}`.toLowerCase().includes(search.trim().toLowerCase()));if(matches.length===1)recordInterest(matches[0].id,'search')},700);return()=>clearTimeout(timer)},[search,feed.events]);
 const [demandKeys,setDemandKeys]=useState<Record<string,string>>({});
 useEffect(()=>{let stopped=false;Promise.all(feed.events.map(async e=>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(e.id));return [e.id,Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,24)]})).then(pairs=>{if(!stopped)setDemandKeys(Object.fromEntries(pairs))}).catch(()=>{});return()=>{stopped=true}},[feed.events]);
 const all=feed.events.filter(e=>active(e,now)).map(e=>({...e,localInterest:interest[demandKeys[e.id]]}));const sorted=all.slice().sort((a,b)=>Date.parse(a.startsAt)-Date.parse(b.startsAt)||a.priority-b.priority);
 const cutoff=now+Number(period)*3600000;const filtered=rankEvents(sorted.filter(e=>(period==='all'||Date.parse(e.startsAt)<cutoff)&&(region==='All Kenya'||e.region===region)&&(category==='All categories'||category==='Entertainment'&&entertainment(e)||e.category===category)&&(source==='All sources'||e.sourceId===source)&&`${e.title} ${e.venue} ${e.sourceName}`.toLowerCase().includes(search.toLowerCase())),{now,region,query:search,mode:sort});
 const own=liveOwn.filter(e=>e.kind==='ticketed'&&e.status==='published'&&e.eventDate&&Date.parse(e.eventDate+'T23:59:59+03:00')>now).sort((a,b)=>b.priority-a.priority);const spotlight=own[0];const heroCandidates=rankEvents(sorted.filter(e=>entertainment(e)&&e.sourceType==='Ticket seller'&&e.region==='Nairobi & nearby'&&e.venue!=='Venue on seller’s page'&&Date.parse(e.startsAt)<now+72*3600000),{now,region:'Nairobi & nearby'});const heroChoices=heroCandidates.filter((e,i,a)=>a.findIndex(x=>x.sourceId===e.sourceId)===i).slice(0,4);const featured=heroChoices.find(e=>e.sourceId===featuredSource)||heroChoices[0];const festivals=rankEvents(sorted.filter(e=>/festival|solfest|fest\b/i.test(e.title)),{now,region}).slice(0,3);const categories=[...new Set(all.map(e=>e.category))].sort();const visibleSources=feed.sources.filter(s=>all.some(e=>e.sourceId===s.id));
 function clear(){setSearch('');setPeriod('72');setRegion('Nairobi & nearby');setCategory('All categories');setSource('All sources');setSort('recommended')}
 return <div className="event-discovery">{notice&&<div className="event-update-notice" role="status"><p>{notice}</p><button type="button" aria-label="Dismiss event update" onClick={()=>setNotice('')}>Close</button></div>}<section className="discovery-intro wrap"><div><p className="eyebrow">Urban Gang Tour · Event discovery</p><h1>What’s happening<br/>in Nairobi?</h1><p>Find your next show. Check the details. Book with the original seller.</p></div><div className="event-intro-actions"><Link href="/organizer/signup" className="button">Host an event</Link><Link href="/contact-us?topic=referrals" className="text-link">Ask about referrals</Link><Link href="/tour-stops" className="discovery-history-link">Our school tour timeline <span aria-hidden="true">→</span></Link></div></section>
 {!spotlight&&heroChoices.length>1&&<div className="wrap entertainment-feature-tabs" aria-label="Featured entertainment sources"><span>Featured entertainment</span>{heroChoices.map(e=><button key={e.sourceId} onClick={()=>setFeaturedSource(e.sourceId)} aria-pressed={featured?.sourceId===e.sourceId}>{e.sourceName}</button>)}</div>}{spotlight?<section className="discovery-feature wrap own-feature"><img src={spotlight.image||'/design-assets/school.jpg'} alt={spotlight.name}/><div><p className="eyebrow">Coming up · Urban Gang Tour</p><h2>{spotlight.name}</h2><p>{spotlight.venue}</p><Link className="button light" href={'/events/'+spotlight.slug}>View our event</Link></div></section>:featured&&<section className="discovery-feature wrap"><Poster e={featured}/><div><p className="eyebrow">Coming up · {featured.sourceName}</p><time dateTime={featured.startsAt}>{formatDate(featured)}</time><h2>{featured.title}</h2><p>{featured.venue}</p><strong>{price(featured)}</strong><a className="button light" onClick={()=>recordInterest(featured.id,'click')} href={featured.url} target="_blank" rel="noopener noreferrer">View tickets on {featured.sourceName}<span aria-hidden="true">→</span></a><small>External event · purchase and ticket support are handled by the seller.</small></div></section>}
 <section className="wrap discovery-layout"><div className="discovery-main"><div className="discovery-controls"><label className="discovery-search"><span>Find an event</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Artist, event or venue"/></label><div className="discovery-selects"><label><span>When</span><select aria-label="When" value={period} onChange={e=>setPeriod(e.target.value)}><option value="72">Next 72 hours</option><option value="168">Next 7 days</option><option value="720">Next 30 days</option><option value="all">All upcoming</option></select></label><label><span>Where</span><select aria-label="Where" value={region} onChange={e=>setRegion(e.target.value)}><option>Nairobi & nearby</option><option>All Kenya</option></select></label><label><span>Category</span><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option><option>Entertainment</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label><span>Source</span><select aria-label="Source" value={source} onChange={e=>setSource(e.target.value)}><option>All sources</option>{visibleSources.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label></div></div>
 <div className="discovery-results-heading"><h2>{period==='72'?'Going out in the next 72 hours':'Find your next event'}</h2><label className="discovery-sort"><span className="sr-only">Sort events</span><select aria-label="Sort events" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="soonest">Soonest</option>{all.some(e=>reportedSales(e,now)!==null)&&<option value="booked">Most booked · reported</option>}</select></label><span role="status" aria-live="polite">{filtered.length} {filtered.length===1?'event':'events'}</span></div><div className="discovery-sync"><span className={state.includes('unavailable')?'sync-dot unavailable':'sync-dot'}/><p>{state}. Last check: <time dateTime={feed.generatedAt}>{new Intl.DateTimeFormat('en-KE',{hour:'numeric',minute:'2-digit',day:'numeric',month:'short',timeZone:'Africa/Nairobi'}).format(new Date(feed.generatedAt))}</time></p></div>
 <p className="discovery-priority-note">Entertainment first: concerts, festivals, club nights and live shows. Other events follow.</p><div className="discovery-grid">{filtered.map(e=><Card e={e} key={e.id} onInterest={recordInterest}/>)}</div>{!filtered.length&&<div className="discovery-empty"><h3>No matches for these filters.</h3><p>Try a different date, search or location.</p>{search.trim()&&<a className="text-link" href={'https://www.google.com/search?q='+encodeURIComponent(search+' events Nairobi Kenya tickets')} target="_blank" rel="noopener noreferrer">Search Google for “{search}” <span aria-hidden="true">→</span></a>}<button className="button" onClick={clear}>Reset filters</button></div>}
 <p className="discovery-disclaimer">Listings come from public event pages. Prices, times and availability may change. Confirm them with the seller before paying.</p></div>
 <aside className="discovery-aside"><section className="festival-rail"><p className="eyebrow">Plan ahead</p><h2>Festival watch.</h2>{festivals.map(e=><a href={e.url} target="_blank" rel="noopener noreferrer" key={e.id}><img src={e.image} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer"/><div><small>{formatDate(e)} · {e.sourceName}</small><h3>{e.title}</h3><span>View event <span aria-hidden="true">→</span></span></div></a>)}</section><section className="discovery-booking"><p className="eyebrow">Your event. Our energy.</p><h2>Planning a school or campus event?</h2><p>Talk to Eugine Micah and Lucy Ogunde about hosting and the full tour experience.</p><Link href="/book" className="button">Plan your event</Link></section><section className="discovery-tour"><p className="eyebrow">On the road</p><h2>The school tour.</h2><ol>{timeline.entries.filter(e=>e.status==='completed').slice(-3).map(e=><li key={e.id}><span className="tour-mini-dot"/><div><strong>{e.name}</strong><small>Completed event</small></div></li>)}</ol><Link href="/tour-stops">See the full timeline <span aria-hidden="true">→</span></Link></section></aside></section>
 <div className="wrap"><ShareActions title="Find entertainment events in Nairobi with Urban Gang Tour" path="/events" label="Share events with a friend"/></div><Newsletter/><section className="wrap events-secondary-actions"><Link href="/contact-us?topic=referrals">Ask about referrals</Link><Link href="/tour-stops">Explore our school tour timeline</Link><Link href="/book">Book Urban Gang Tour</Link></section><section className="wrap discovery-sources"><div><p className="eyebrow">Choose the right seller</p><h2>Ticket sellers & event guides.</h2><p>Kenyan platforms come first. A directory link means no live listing feed is connected.</p></div><div className="source-directory">{feed.sources.map(s=><a href={s.url} target="_blank" rel="noopener noreferrer" key={s.id}><strong>{s.name}<span aria-hidden="true">→</span></strong><small>{s.type} · {s.scope==='Guide'?'Kenya listings':s.scope}</small><span className={'source-state '+(s.count>0?'connected':'')}>{s.count>0?s.status:'Directory link'}</span></a>)}</div><p className="discovery-disclaimer">Independent sources are not sponsors or partners unless explicitly stated. Live checks run every three minutes while this page is open; individual sources may be delayed or unavailable.</p></section></div>
}
