 'use client';
import {useEffect,useRef,useState} from 'react';
export function useDock(){
 const [dock,setDock]=useState<{x:number;y:number;side:string}|null>(null);
 const root=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;left:number;top:number;active:boolean;pointer:number;target:HTMLElement}|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),suppress=useRef(false);
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);timer.current=null;const d=drag.current;if(d?.target.hasPointerCapture(d.pointer))d.target.releasePointerCapture(d.pointer);drag.current=null};
 const place=(x:number,y:number,snap=false)=>{const b=root.current?.getBoundingClientRect(),width=b?.width||290,height=b?.height||140;const side=x+width/2<innerWidth/2?'left':'right';const next={x:snap?(side==='left'?12:Math.max(12,innerWidth-width-12)):Math.max(12,Math.min(x,innerWidth-width-12)),y:Math.max(88,Math.min(y,Math.max(88,innerHeight-height-16))),side};setDock(next);return next};
 const save=(next:NonNullable<typeof dock>)=>{try{localStorage.setItem('ugt-talk-dock',JSON.stringify(next))}catch{}};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('ugt-talk-dock')||'null');if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y))place(saved.x,saved.y,true)}catch{}const resize=()=>setDock(previous=>{if(!previous)return null;const b=root.current?.getBoundingClientRect();return {...previous,x:previous.side==='left'?12:Math.max(12,innerWidth-(b?.width||290)-12),y:Math.min(previous.y,Math.max(88,innerHeight-(b?.height||140)-16))}});window.addEventListener('resize',resize);return()=>{cancel();window.removeEventListener('resize',resize)}},[]);
 const handle={onPointerDown:(e:React.PointerEvent<HTMLDivElement>)=>{if(e.button!==0||(e.target as HTMLElement).closest('a,.floating-talk-controls'))return;cancel();suppress.current=false;const b=root.current?.getBoundingClientRect();if(!b)return;drag.current={x:e.clientX,y:e.clientY,left:b.left,top:b.top,active:false,pointer:e.pointerId,target:e.currentTarget};timer.current=setTimeout(()=>{const d=drag.current;if(d){d.active=true;d.target.setPointerCapture(d.pointer);suppress.current=true}},420)},onPointerMove:(e:React.PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d)return;if(!d.active){if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>10)cancel();return}e.preventDefault();place(d.left+e.clientX-d.x,d.top+e.clientY-d.y)},onPointerUp:(e:React.PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(d?.active)save(place(d.left+e.clientX-d.x,d.top+e.clientY-d.y,true));cancel()},onPointerCancel:cancel,onClickCapture:(e:React.MouseEvent<HTMLDivElement>)=>{if(suppress.current){e.preventDefault();e.stopPropagation();suppress.current=false}},onContextMenu:(e:React.MouseEvent<HTMLDivElement>)=>{if(drag.current)e.preventDefault()},onKeyDown:(e:React.KeyboardEvent<HTMLDivElement>)=>{if(!e.altKey||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const b=root.current?.getBoundingClientRect();if(b)save(place(e.key==='ArrowLeft'?0:e.key==='ArrowRight'?innerWidth:b.left,b.top+(e.key==='ArrowUp'?-60:e.key==='ArrowDown'?60:0),e.key==='ArrowLeft'||e.key==='ArrowRight'))}};
 return {root,dock,handle};
}
