"use client";
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import routes from '../../data/public-design-routes.json';
import {ContactFooter,FloatingTalk} from '../../public-design/components/ContactInterface';
const links=[['About','/about'],['Account','/account'],['Book us','/book'],['Events','/events'],['Gallery','/gallery'],['Home','/'],['News','/blog'],['Portfolio','/portfolio'],['Reels','/reels'],['Shop','/shop'],['Contact','/contact-us']];
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const [focus,setFocus]=useState(false);useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('ugt-new-preview-v1focusView')||'false');setFocus(value);document.documentElement.dataset.focusView=String(value)}catch{}},[]);const [open,setOpen]=useState(false);const trigger=useRef<HTMLButtonElement>(null);
useEffect(()=>{setOpen(false)},[path]);
useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const nodes=()=>Array.from(document.querySelectorAll<HTMLElement>('#app-menu a,#app-menu button'));nodes()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}if(e.key==='Tab'){const items=nodes();const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',key)}},[open]);
if(path.startsWith('/admin')||path.startsWith('/organizer/dashboard')||path==='/offline')return <div id="main-content" tabIndex={-1}>{children}</div>;
if((routes as string[]).includes(path.replace(/\/$/,'')||'/'))return <>{children}</>;
const admin=path.startsWith('/admin');
return <><header className="site-header"><a className="brand" href="/" aria-label="Urban Gang Tour home"><img src="/assets/ugt-logo.png" alt="Urban Gang Tour"/></a><nav className="desktop-nav" aria-label="Main navigation">{links.filter(([label])=>!['Account','Book us','Home'].includes(label)).map(([label,href])=><a key={href} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}</nav><div className="header-actions"><a className="cart-link" href="/cart">Bag</a><a className="start-link" href="/book">Book <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19L19 5M5 5h14v14" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></a><button ref={trigger} className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="app-menu" onClick={()=>setOpen(x=>!x)}><span className="menu-label">{open?'Close':'Explore'}</span><span className={open?'burger is-open':'burger'} aria-hidden="true"><i/><i/><i/></span></button></div></header>{open&&<><button className="menu-shade is-open" aria-label="Close navigation" onClick={()=>setOpen(false)}/><div id="app-menu" className="menu-panel is-open" role="dialog" aria-modal="true" aria-label="Site navigation"><nav>{links.map(([label,href],index)=><a key={href} href={href}><small>{String(index+1).padStart(2,'0')}</small><span>{label}</span><svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></a>)}</nav><a href="/organizer/login">Organizer portal</a><button className="button" onClick={()=>{setOpen(false);trigger.current?.focus()}}>Close menu</button></div></>}
<div id="main-content" className={!path.startsWith('/organizer/')&&!['/shop','/cart','/checkout','/book','/account','/pay/success'].includes(path)?'application-content with-header-space':'application-content'} tabIndex={-1}>{children}</div>{!admin&&!path.startsWith('/checkout')&&<ContactFooter onCookies={()=>window.dispatchEvent(new Event('ugt-open-cookie-settings'))} focusView={focus} onFocus={()=>{const value=!focus;setFocus(value);try{localStorage.setItem('ugt-new-preview-v1focusView',JSON.stringify(value))}catch{}document.documentElement.dataset.focusView=String(value);window.dispatchEvent(new CustomEvent('ugt-focus-view',{detail:value}))}} form={false}/>}{!admin&&!path.startsWith('/checkout')&&!path.startsWith('/pay/')&&!['/book','/account','/cart'].includes(path)&&<FloatingTalk/>}</>}
