'use client';
import {useEffect,useRef,useState} from 'react';
import {fetchWithTimeout} from '@/lib/client/fetch-with-timeout';
const types=[['School Booking','School event'],['Campus Rave','Campus event'],['Mega Event','Live or public event'],['Media','Hosts or brand campaign'],['Sponsorship','Sponsorship'],['Partnership','Partnership'],['Join the Crew','Join the crew']];
export function BookingForm(){
  const [form,setForm]=useState({name:'',org:'',email:'',phone:'',type:'School Booking',message:'',preferredDate:'',expectedAttendance:'',schoolContactConfirmed:false});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[id,setId]=useState(''),[statusToken,setStatusToken]=useState('');const request=useRef(''),pending=useRef(false);
  useEffect(()=>{try{const draft=JSON.parse(sessionStorage.getItem('ugt-booking-draft')||'null');if(draft&&typeof draft==='object')setForm(f=>({...f,...Object.fromEntries(Object.entries(draft).filter(([k,v])=>k in f&&(typeof v==='string'||typeof v==='boolean')))}));}catch{}const q=new URLSearchParams(location.search),type=({school:'School Booking',campus:'Campus Rave',public:'Mega Event',hosts:'Media',commercial:'Media'} as Record<string,string>)[q.get('type')||''];if(type)setForm(f=>({...f,type}));},[]);
  function update(field:string,value:string|boolean){setForm(f=>{const next={...f,[field]:value};try{sessionStorage.setItem('ugt-booking-draft',JSON.stringify(next))}catch{}return next});request.current=''}
  async function submit(e:React.FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError('');if(!request.current)request.current=crypto.randomUUID();try{const r=await fetchWithTimeout('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,preferredDate:form.preferredDate||undefined,expectedAttendance:form.expectedAttendance?Number(form.expectedAttendance):undefined,requestId:request.current})});const d=await r.json();if(r.ok&&d.ok&&d.id){setId(d.id);setStatusToken(d.statusToken||'');try{sessionStorage.removeItem('ugt-booking-draft')}catch{}}else setError('We could not save your request. Your details are kept. Please try again or contact us.')}catch{setError('Connection interrupted. Your details are kept. Retry to send the same request.')}finally{setBusy(false);pending.current=false}}
  return <section className="booking2 wrap"><div className="booking2-pitch"><p className="eyebrow">Plan it with us</p><h1>Your audience.<br/>An event to remember.</h1><p>Book Eugine Micah and Lucy Ogunde for your school, campus or live event. Tell us the essentials. We’ll discuss the right programme and quote.</p><ol className="booking-steps"><li><strong>Share your brief.</strong><span>Your audience, venue and what you have in mind.</span></li><li><strong>Plan it together.</strong><span>Discuss hosts, production, dates and costs.</span></li><li><strong>Confirm your event.</strong><span>Agree the scope and payment before the date is reserved.</span></li></ol><a className="text-link" href="/portfolio">See what we’ve delivered</a><div className="booking-direct"><p>Prefer a quick conversation?</p><a href="https://wa.me/254799886247?text=Hello%20Urban%20Gang%20Tour%2C%20I%20would%20like%20to%20plan%20an%20event." target="_blank" rel="noopener noreferrer"><img src="/design-assets/social/whatsapp.svg" width="20" height="20" alt=""/>Chat on WhatsApp</a></div></div>
  <div>{id?<div className="modern-card booking-confirmation" role="status"><p className="eyebrow">Request received</p><h2>Let’s plan the next step.</h2><p>Your reference: <strong>{id}</strong></p><p>The team will contact you using the details you provided. Your date is confirmed after we agree the plan and payment.</p>{statusToken&&<a className="button" href={"/book/status?token="+encodeURIComponent(statusToken)}>Check your enquiry progress</a>}<a className="button" href="/portfolio">Explore our work</a><a className="text-link" href="/">Back to the tour</a></div>:<form className="modern-form booking2-form" onSubmit={submit} aria-busy={busy}><h2>What are you planning?</h2><p className="modern-muted">No payment is needed to send an enquiry.</p><label>Event type<select value={form.type} onChange={e=>update('type',e.target.value)}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Your name<input name="name" required minLength={2} maxLength={100} autoComplete="name" value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>{form.type==='School Booking'?'School or institution':'Organization (optional)'}<input name="org" required={form.type==='School Booking'} maxLength={100} autoComplete="organization" value={form.org} onChange={e=>update('org',e.target.value)}/></label><label>Email<input name="email" required type="email" maxLength={254} autoComplete="email" value={form.email} onChange={e=>update('email',e.target.value)}/></label><label>Tell us about your event<textarea name="message" required minLength={10} maxLength={3000} rows={3} placeholder="Audience, location and what you want to make happen" value={form.message} onChange={e=>update('message',e.target.value)}/></label>
    <details className="booking-extras"><summary>Add a phone number, date or audience size <small>Optional</small></summary><div><label>Phone (optional)<input name="phone" type="tel" autoComplete="tel" maxLength={20} value={form.phone} onChange={e=>update('phone',e.target.value)}/></label><label>Preferred date (optional)<input name="preferredDate" type="date" value={form.preferredDate} onChange={e=>update('preferredDate',e.target.value)}/></label><label>Expected audience (optional)<input name="expectedAttendance" type="number" min={1} max={500000} value={form.expectedAttendance} onChange={e=>update('expectedAttendance',e.target.value)}/></label></div></details>
    {form.type==='School Booking'&&<label className="checkbox"><input required type="checkbox" checked={form.schoolContactConfirmed} onChange={e=>update('schoolContactConfirmed',e.target.checked)}/><span>I am an adult authorized to arrange this school event.</span></label>}<label className="checkbox"><input required type="checkbox"/><span>I agree to the <a href="/privacy-policy">privacy policy</a> for handling this enquiry.</span></label>{error&&<div className="modern-alert" role="alert">{error} <a href="/contact-us">Contact the team</a></div>}<button className="button" disabled={busy}>{busy?'Sending your brief…':'Request my event quote'}</button><p className="modern-muted">We’ll discuss availability and costs with you. Sending this form does not reserve a date.</p></form>}</div></section>;
}
