'use client';
import {readLiveCart,addCartItem,LIVE_CART_KEY} from '@/lib/client/live-cart';
import {useEffect,useRef,useState} from 'react';
import {fetchWithTimeout} from '@/lib/client/fetch-with-timeout';
type Product={id:string;name:string;price:number;image?:string;description?:string;variants:{label:string;priceAdjustment:number;sku?:string}[]};
type Item={id:string;qty:number;variant?:string};
type Event={id:string;name:string;sellable?:boolean;tiers:{name:string;price:number}[]};
const storage=LIVE_CART_KEY;
const money=(n:number)=>'KES '+n.toLocaleString('en-KE');
export function LiveCommerce({view='shop',eventId}:{view?:'shop'|'cart'|'checkout';eventId?:string}){
 const [search,setSearch]=useState('');const [sort,setSort]=useState('featured');
 const [selected,setSelected]=useState('');const [products,setProducts]=useState<Product[]>([]);const [event,setEvent]=useState<Event>();const [items,setItems]=useState<Item[]>([]);const [ready,setReady]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [retry,setRetry]=useState(0);const [tier,setTier]=useState(0);const [qty,setQty]=useState(1);const [variants,setVariants]=useState<Record<string,string>>({});const [method,setMethod]=useState('mpesa');const [promo,setPromo]=useState('');const [busy,setBusy]=useState(false);const pending=useRef(false);const key=useRef('');const [form,setForm]=useState({name:'',email:'',phone:''});
 useEffect(()=>{setSelected(new URLSearchParams(location.search).get('item')||'');setItems(readLiveCart());setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(storage,JSON.stringify(items))}catch{setNotice('Your browser cannot save this bag. Keep this page open.')}},[items,ready]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetchWithTimeout(eventId?'/api/site-data/events':'/api/site-data/products',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(!d.ok)throw Error();if(eventId)setEvent(d.events?.find((e:Event)=>e.id===eventId));else setProducts(d.products||[])}).catch(()=>{if(!controller.signal.aborted)setError('We could not load the live catalogue. Try again.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[eventId,retry]);
 const productFor=(item:Item)=>products.find(p=>p.id===item.id);const amount=(item:Item)=>{const p=productFor(item);return (p?.price||0)+(p?.variants.find(v=>v.label===item.variant)?.priceAdjustment||0)};
 const unavailable=items.some(i=>!productFor(i)||(!!i.variant&&!productFor(i)?.variants.some(v=>v.label===i.variant)));
 const total=eventId?(event?.tiers[tier]?.price||0)*qty:items.reduce((sum,i)=>sum+amount(i)*i.qty,0);
 function add(p:Product){const variant=variants[p.id]||p.variants[0]?.label;setItems(old=>addCartItem(old,{id:p.id,qty:1,variant}));key.current='';setNotice(p.name+' added to your bag.')}
 async function pay(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current)return;if(eventId?(!event?.sellable||!event.tiers[tier]):(!items.length||unavailable)){setError('This selection is unavailable. Review your bag before paying.');return}pending.current=true;setBusy(true);setError('');if(!key.current)key.current=crypto.randomUUID();
 try{if(method==='card'&&!eventId){const payload={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,email:form.email||undefined,promoCode:promo||undefined})};let r=await fetchWithTimeout('/api/paystack/checkout',payload);let d=await r.json();if(d.error==='card_not_configured'){r=await fetchWithTimeout('/api/stripe/checkout',payload);d=await r.json()}const url=d.authorizationUrl||d.url;if(r.ok&&typeof url==='string'&&new URL(url).protocol==='https:'){if(d.orderId||d.id)try{sessionStorage.setItem('ugt-checkout-order',JSON.stringify({id:d.orderId||d.id,items}))}catch{}window.location.assign(url);return}setError('Card checkout is unavailable. Your bag is kept. You can use M-Pesa or try again later.');return}const r=await fetchWithTimeout('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,email:form.email||undefined,idempotencyKey:key.current,promoCode:promo||undefined,...(eventId?{ticket:{eventId,tier,qty}}:{items})})});const d=await r.json();if(d.id){try{sessionStorage.setItem('ugt-checkout-order',JSON.stringify({id:d.id,items,eventId}))}catch{}window.location.assign('/pay/success?ref='+encodeURIComponent(d.id));return}setError(d.error==='invalid_phone'?'Enter a valid Kenyan M-Pesa number.':d.error==='out_of_stock'?'This selection is out of stock. Review your bag.':'We could not start payment. Your details are kept. Try again.');}catch{setError(method==='card'?'Connection interrupted. Check for a payment confirmation before trying card checkout again.':'Connection interrupted. Retry with the same details. We reuse your request to avoid a duplicate charge.')}finally{pending.current=false;setBusy(false)}}
 return <section className="modern-page"><p className="eyebrow">{eventId?'Tickets':'Urban Gang merchandise'}</p><h1>{eventId?(event?.name||'Your event tickets'):view==='shop'?'Wear the culture.':view==='cart'?'Your bag.':'Checkout.'}</h1><div className="modern-actions">{selected&&<a href="/shop">View all merchandise</a>}<a href={view==='shop'?'/events':'/shop'}>{view==='shop'?'Explore events':'← Continue shopping'}</a>{view==='shop'&&<a className="button" href="/cart">View bag ({items.reduce((n,i)=>n+i.qty,0)})</a>}</div>{notice&&<p role="status">{notice} <a href="/cart">View bag</a></p>}{loading&&<p role="status">Loading the live catalogue…</p>}{error&&<div className="modern-alert" role="alert">{error} {!busy&&<button type="button" onClick={()=>setRetry(n=>n+1)}>Reload catalogue</button>}</div>}
 {!loading&&!error&&view==='shop'&&!products.length&&<div className="modern-card"><h2>The next drop is being prepared.</h2><p>There are no products available to purchase right now.</p><a className="button" href="/contact-us">Ask about merchandise</a></div>}
 {view==='shop'&&products.length>0&&<div className="shop-tools live-shop-tools"><label>Find merchandise<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="T-shirt, cap, bag…"/></label><label>Sort products<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>}
 {view==='shop'&&<div className="modern-grid live-shop-grid" style={{marginTop:32}}>{products.filter(p=>(!selected||p.id===selected)&&`${p.name} ${p.description||''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0).map(p=><article className="modern-card shop-product-card" key={p.id}>{p.image&&<a className="product-image" href={'/shop/'+encodeURIComponent(p.id)}><img src={p.image} alt={p.name} loading="lazy"/></a>}<h2><a href={'/shop/'+encodeURIComponent(p.id)}>{p.name}</a></h2><p>{p.description}</p><p>{money(p.price+(p.variants.find(v=>v.label===(variants[p.id]||p.variants[0]?.label))?.priceAdjustment??0))}</p>{!!p.variants.length&&<label>Choose a variation<select aria-label={'Variation for '+p.name} value={variants[p.id]||p.variants[0].label} onChange={e=>setVariants({...variants,[p.id]:e.target.value})}>{p.variants.map(v=><option key={v.label}>{v.label}</option>)}</select></label>}<button className="button" onClick={()=>add(p)}>Add to bag</button></article>)}</div>}
 {view!=='shop'&&!eventId&&ready&&<div style={{marginTop:32}}>{!items.length?<p>Your bag is empty. <a href="/shop">Explore merchandise</a></p>:<>{items.map((i,index)=><article className="modern-card" key={i.id+'-'+i.variant} style={{marginBottom:16}}><h2>{productFor(i)?.name||'Product unavailable'}</h2><p>{i.variant} · {money(amount(i))} each</p><label>Quantity <input aria-label={'Quantity for '+(productFor(i)?.name||i.id)} type="number" min={1} max={20} value={i.qty} onChange={e=>{setItems(old=>old.map((x,n)=>n===index?{...x,qty:Math.min(20,Math.max(1,Number(e.target.value)||1))}:x));key.current=''}}/></label><button type="button" onClick={()=>{setItems(old=>old.filter((_,n)=>n!==index));key.current=''}}>Remove</button></article>)}{unavailable&&!loading&&<p role="alert">Remove unavailable products or variations before checkout.</p>}<h2>Total {money(total)}</h2>{view==='cart'&&!unavailable&&!loading&&<a className="button" href="/checkout">Continue to secure checkout</a>}</>}</div>}
 {eventId&&!loading&&(!event||!event.sellable)&&<p>Ticket sales are not open for this event. <a href="/events">Find another event</a></p>}
 {(view==='checkout'||eventId)&&!loading&&(eventId?event?.sellable:items.length>0&&!unavailable)&&<form className="modern-form" onSubmit={pay} style={{marginTop:32}}>{event&&<><label>Ticket tier<select value={tier} onChange={e=>{setTier(Number(e.target.value));key.current=''}}>{event.tiers.map((t,i)=><option key={i} value={i}>{t.name} · {money(t.price)}</option>)}</select></label><label>Tickets<input type="number" min={1} max={20} value={qty} onChange={e=>{setQty(Math.min(20,Math.max(1,Number(e.target.value)||1)));key.current=''}}/></label><h2>Total {money(total)}</h2></>}{!eventId&&<label>Payment method<select value={method} onChange={e=>{setMethod(e.target.value);key.current=''}}><option value="mpesa">M-Pesa</option><option value="card">Card</option></select></label>}{((method==='card'?['email']:['name','phone','email']) as ('name'|'phone'|'email')[]).map(field=><label key={field}>{field==='name'?'Your full name':field==='phone'?'M-Pesa phone number':'Email for your receipt (optional)'}<input name={field} required={field!=='email'} type={field==='email'?'email':field==='phone'?'tel':'text'} autoComplete={field==='phone'?'tel':field} minLength={field==='name'?2:undefined} maxLength={field==='name'?100:field==='email'?254:20} value={form[field]} onChange={e=>{setForm({...form,[field]:e.target.value});key.current=''}}/></label>)}{!eventId&&<label>Promo code (optional)<input maxLength={60} value={promo} onChange={e=>{setPromo(e.target.value);key.current=''}}/></label>}<label className="checkbox"><input type="checkbox" required/> <span>I accept the <a href="/terms" target="_blank" rel="noopener">terms</a>, <a href="/refund-policy" target="_blank" rel="noopener">refund policy</a> and <a href="/privacy-policy" target="_blank" rel="noopener">privacy policy</a>.</span></label><p>{method==='card'?'You’ll open the secure card checkout. Your receipt is issued only after payment is confirmed.':'You’ll receive an M-Pesa prompt on your phone. Your ticket or receipt is issued only after payment is confirmed.'}</p><button className="button" disabled={busy}>{busy?'Starting secure payment…':method==='card'?'Continue to secure card payment':'Pay '+money(total)+' with M-Pesa'}</button></form>}
 </section>
}
