'use client';
import {useState} from 'react';
import {readLiveCart,addCartItem,LIVE_CART_KEY} from '@/lib/client/live-cart';
type Variant={label:string;priceAdjustment:number;stock?:number|null};
export function ProductPurchase({id,price,variants,stock}:{id:string;price:number;variants:Variant[];stock?:number|null}){
 const [variant,setVariant]=useState(variants.find(v=>v.stock!==0)?.label||variants[0]?.label||''),[qty,setQty]=useState(1),[notice,setNotice]=useState(''),[added,setAdded]=useState(false);
 const total=(price+(variants.find(v=>v.label===variant)?.priceAdjustment||0))*qty;
 function add(){if(stock===0||variants.find(v=>v.label===variant)?.stock===0)return;try{const cart=addCartItem(readLiveCart(),{id,qty,...(variant?{variant}:{})});localStorage.setItem(LIVE_CART_KEY,JSON.stringify(cart));setAdded(true);setNotice('Added to your cart. Review your items before paying.')}catch{setNotice('Your browser could not save the cart. Allow site storage and try again.')}}
 return <div className="product-purchase">{!!variants.length&&<label>Choose your options<select aria-label="Product options" value={variant} onChange={e=>{setVariant(e.target.value);setAdded(false);setNotice('')}}>{variants.map(v=><option key={v.label} value={v.label} disabled={v.stock===0}>{v.label}{v.stock===0?' · Out of stock':''}{v.priceAdjustment?' · '+(v.priceAdjustment>0?'+':'')+'KES '+v.priceAdjustment.toLocaleString('en-KE'):''}</option>)}</select></label>}<label>Quantity<input aria-label="Product quantity" type="number" min={1} max={20} value={qty} onChange={e=>{setQty(Math.max(1,Math.min(20,Number(e.target.value)||1)));setAdded(false);setNotice('')}}/></label><p>{typeof stock==='number'?(stock>0?stock+' available':'Out of stock'):'Availability is checked at checkout.'}</p><button className="button" disabled={stock===0||variants.find(v=>v.label===variant)?.stock===0} onClick={add}>Add to cart · KES {total.toLocaleString('en-KE')}</button>{notice&&<p role="status">{notice}</p>}{added&&<a className="button secondary" href="/cart">Review your cart</a>}<p className="form-note">Choose your options, review your cart, then pay by M-Pesa or supported card checkout. Payment confirmation completes your order.</p><details><summary>Returns and refunds</summary><p>Read the <a href="/refund-policy">refund policy</a> before paying.</p></details></div>
}
