import {NextResponse} from 'next/server';
import {randomBytes} from 'node:crypto';
import {hasDb,q} from '@/lib/server/db';
import {validatedCurrentBuyer} from '@/lib/server/customer-account';
import {sameOrigin} from '@/lib/server/origin';
import {rateLimit,clientIp} from '@/lib/server/ratelimit';
import {affiliateProgram,ensureAffiliateLedger,affiliateEarnings} from '@/lib/server/affiliate-program';
export const dynamic='force-dynamic';
// Buyers may create/read only their own application. Accepted terms are versioned.
export async function GET(req:Request){const user=await validatedCurrentBuyer(req).catch(()=>null);if(!user)return NextResponse.json({error:'sign_in_required'},{status:401});if(!rateLimit('affiliate-read:'+clientIp(req),30,60000,req))return NextResponse.json({error:'too_many_requests'},{status:429});if(!hasDb())return NextResponse.json({error:'unavailable'},{status:503});try{await ensureAffiliateLedger();const rows=await q('SELECT id,status,name,audience,accepted_terms_version FROM affiliate_codes WHERE user_id=$1',[user.id]);return NextResponse.json({application:rows[0]||null,program:await affiliateProgram(),earnings:rows[0]?await affiliateEarnings(rows[0].id):null},{headers:{'Cache-Control':'private, no-store'}})}catch{return NextResponse.json({error:'unavailable'},{status:503})}}
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'bad_origin'},{status:403});const user=await validatedCurrentBuyer(req).catch(()=>null);if(!user)return NextResponse.json({error:'sign_in_required'},{status:401});if(!rateLimit('affiliate:'+clientIp(req),5,60000,req))return NextResponse.json({error:'too_many_requests'},{status:429});const body=await req.json().catch(()=>null);if(!body||Object.keys(body).some(k=>!['name','audience','termsVersion'].includes(k))||typeof body.name!=='string'||!body.name.trim()||body.name.length>100||typeof body.audience!=='string'||body.audience.trim().length<10||body.audience.length>1000||body.termsVersion!==undefined&&(typeof body.termsVersion!=='string'||body.termsVersion.length>80))return NextResponse.json({error:'invalid_application'},{status:400});if(!hasDb())return NextResponse.json({error:'unavailable'},{status:503});try{await ensureAffiliateLedger();const program=await affiliateProgram();if(body.termsVersion&&(!program.enabled||body.termsVersion!==program.termsVersion))return NextResponse.json({error:'terms_changed'},{status:409});const rows=await q(`INSERT INTO affiliate_codes(id,user_id,name,audience,accepted_terms_version,accepted_at) VALUES($1,$2,$3,$4,$5,CASE WHEN $5::text IS NULL THEN NULL ELSE now() END) ON CONFLICT(user_id) DO UPDATE SET name=EXCLUDED.name,audience=EXCLUDED.audience,accepted_terms_version=COALESCE(EXCLUDED.accepted_terms_version,affiliate_codes.accepted_terms_version),accepted_at=CASE WHEN EXCLUDED.accepted_terms_version IS NULL THEN affiliate_codes.accepted_at ELSE now() END RETURNING id,status,name,audience,accepted_terms_version`,[randomBytes(12).toString('hex'),user.id,body.name.trim(),body.audience.trim(),body.termsVersion||null]);return NextResponse.json({application:rows[0],program})}catch{return NextResponse.json({error:'unavailable'},{status:503})}}
